version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 dmoj.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dmoj
      POSTGRES_USER: dmoj_user
      POSTGRES_PASSWORD: dmoj_pass

volumes:
  pgdata:

